spring:
  config:
    activate:
      on-profile: dev

  kafka:
    bootstrap-servers: host.docker.internal:9092
    consumer:
      group-id: complaint-consumers-dev

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/complaint_db
    username: complaint_user
    password: complaint_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
